@startuml
start

:Initial State;
note right
  Node1 (10 RAM)
  Node2 (6 RAM)
  Node3 (10 RAM)
  Node4 (6 RAM)
end note

:Execute Task1 (5 RAM);
note right
  Node1 (5 RAM)
  Node2 (6 RAM)
  Node3 (10 RAM)
  Node4 (6 RAM)
end note

:Execute Task2 (6 RAM);
note right
  Node1 (5 RAM)
  Node3 (10 RAM)
  Node4 (6 RAM)
end note

:Execute Task3 (5 RAM);
note right
  Node3 (10 RAM)
  Node4 (6 RAM)
end note

:Execute Task4 (5 RAM);
note right
  Node3 (5 RAM)
  Node4 (6 RAM)
end note

:Execute Task5 (3 RAM);
note right
  Node3 (5 RAM)
  Node4 (3 RAM)
end note

:Execute Task6 (2 RAM);
note right
  Node3 (3 RAM)
  Node4 (3 RAM)
end note

stop
@enduml